### ISSUE TITLE
Twitter Handle for Tweet on Taiko's Twitter

### ISSUE THREAD

**Issue by 2manslkh** [nolifelover/ethsingapore-social-bureau#1]
@nolifelover 

Congratulations on winning our bounty on Taiko :)

Could you provide me the twitter handles of your project so that we can promote it?

Thanks!

**Comment by nolifelover** [comment]
> @nolifelover
> 
> Congratulations on winning our bounty on Taiko :)
> 
> Could you provide me the twitter handles of your project so that we can promote it?
> 
> Thanks!

Thank you @2manslkh My team will contact you while TG. I Love Taiko.
